[env:m5stack-cores3]
platform = espressif32
board = m5stack-cores3
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_flags = 
  -DBOARD_HAS_PSRAM
  -mfix-esp32-psram-cache-issue
  -DCONFIG_SPIRAM_SUPPORT=1
  -DCONFIG_SPIRAM_USE_MALLOC=1
  -DCONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL=16384
  -DCONFIG_SPIRAM_MALLOC_RESERVE_INTERNAL=32768

lib_deps =
  m5stack/M5CoreS3 @ ^2.0.5
  m5stack/M5Module-LLM
  links2004/WebSockets @ ^2.4.1
  bblanchon/ArduinoJson @ ^7.0.4
  esphome/ESP32-audioI2S @ ^2.0.7

lib_ldf_mode = deep+
board_build.partitions = huge_app.csv